// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.site.getDomains
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::place_wisp::v2::site::get_domains;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetDomains<S: BosStr = DefaultStr> {
    pub did: Did<S>,
    pub rkey: RecordKey<Rkey<S>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetDomainsOutput<S: BosStr = DefaultStr> {
    pub domains: Vec<get_domains::SiteDomain<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct SiteDomain<S: BosStr = DefaultStr> {
    pub domain: S,
    pub kind: SiteDomainKind<S>,
    pub status: SiteDomainStatus<S>,
    pub verified: bool,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_site_domain_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SiteDomainKind<S: BosStr = DefaultStr> {
    Wisp,
    Custom,
    Other(S),
}

impl<S: BosStr> SiteDomainKind<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Wisp => "wisp",
            Self::Custom => "custom",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "wisp" => Self::Wisp,
            "custom" => Self::Custom,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for SiteDomainKind<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for SiteDomainKind<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for SiteDomainKind<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for SiteDomainKind<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for SiteDomainKind<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for SiteDomainKind<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = SiteDomainKind<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            SiteDomainKind::Wisp => SiteDomainKind::Wisp,
            SiteDomainKind::Custom => SiteDomainKind::Custom,
            SiteDomainKind::Other(v) => SiteDomainKind::Other(v.into_static()),
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SiteDomainStatus<S: BosStr = DefaultStr> {
    PendingVerification,
    Verified,
    Other(S),
}

impl<S: BosStr> SiteDomainStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::PendingVerification => "pendingVerification",
            Self::Verified => "verified",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "pendingVerification" => Self::PendingVerification,
            "verified" => Self::Verified,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for SiteDomainStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for SiteDomainStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for SiteDomainStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for SiteDomainStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for SiteDomainStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for SiteDomainStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = SiteDomainStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            SiteDomainStatus::PendingVerification => {
                SiteDomainStatus::PendingVerification
            }
            SiteDomainStatus::Verified => SiteDomainStatus::Verified,
            SiteDomainStatus::Other(v) => SiteDomainStatus::Other(v.into_static()),
        }
    }
}

/** Response marker for the `place.wisp.v2.site.getDomains` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetDomainsOutput<S>` for this endpoint.*/
pub struct GetDomainsResponse;
impl jacquard_common::xrpc::XrpcResp for GetDomainsResponse {
    const NSID: &'static str = "place.wisp.v2.site.getDomains";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetDomainsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetDomains<S> {
    const NSID: &'static str = "place.wisp.v2.site.getDomains";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetDomainsResponse;
}

/** Endpoint marker for the `place.wisp.v2.site.getDomains` query.

Path: `/xrpc/place.wisp.v2.site.getDomains`. The request payload type is `GetDomains<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetDomainsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetDomainsRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.site.getDomains";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetDomains<S>;
    type Response = GetDomainsResponse;
}

impl<S: BosStr> LexiconSchema for SiteDomain<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.site.getDomains"
    }
    fn def_name() -> &'static str {
        "siteDomain"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_site_getDomains()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.domain;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 253usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("domain"),
                    max: 253usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.domain;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 3usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("domain"),
                    min: 3usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod get_domains_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
        type Rkey;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
        type Rkey = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Did = Set<members::did>;
        type Rkey = St::Rkey;
    }
    ///State transition - sets the `rkey` field to Set
    pub struct SetRkey<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRkey<St> {}
    impl<St: State> State for SetRkey<St> {
        type Did = St::Did;
        type Rkey = Set<members::rkey>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
        ///Marker type for the `rkey` field
        pub struct rkey(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetDomainsBuilder<St: get_domains_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Did<S>>, Option<RecordKey<Rkey<S>>>),
    _type: PhantomData<fn() -> S>,
}

impl GetDomains<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetDomainsBuilder<get_domains_state::Empty, DefaultStr> {
        GetDomainsBuilder::new()
    }
}

impl<S: BosStr> GetDomains<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetDomainsBuilder<get_domains_state::Empty, S> {
        GetDomainsBuilder::builder()
    }
}

impl GetDomainsBuilder<get_domains_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetDomainsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetDomainsBuilder<get_domains_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetDomainsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetDomainsBuilder<St, S>
where
    St: get_domains_state::State,
    St::Did: get_domains_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<S>>,
    ) -> GetDomainsBuilder<get_domains_state::SetDid<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetDomainsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetDomainsBuilder<St, S>
where
    St: get_domains_state::State,
    St::Rkey: get_domains_state::IsUnset,
{
    /// Set the `rkey` field (required)
    pub fn rkey(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> GetDomainsBuilder<get_domains_state::SetRkey<St>, S> {
        self._fields.1 = Option::Some(value.into());
        GetDomainsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetDomainsBuilder<St, S>
where
    St: get_domains_state::State,
    St::Did: get_domains_state::IsSet,
    St::Rkey: get_domains_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetDomains<S> {
        GetDomains {
            did: self._fields.0.unwrap(),
            rkey: self._fields.1.unwrap(),
        }
    }
}

fn deserialize_site_domain_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}

pub mod site_domain_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Domain;
        type Kind;
        type Status;
        type Verified;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Domain = Unset;
        type Kind = Unset;
        type Status = Unset;
        type Verified = Unset;
    }
    ///State transition - sets the `domain` field to Set
    pub struct SetDomain<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDomain<St> {}
    impl<St: State> State for SetDomain<St> {
        type Domain = Set<members::domain>;
        type Kind = St::Kind;
        type Status = St::Status;
        type Verified = St::Verified;
    }
    ///State transition - sets the `kind` field to Set
    pub struct SetKind<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetKind<St> {}
    impl<St: State> State for SetKind<St> {
        type Domain = St::Domain;
        type Kind = Set<members::kind>;
        type Status = St::Status;
        type Verified = St::Verified;
    }
    ///State transition - sets the `status` field to Set
    pub struct SetStatus<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStatus<St> {}
    impl<St: State> State for SetStatus<St> {
        type Domain = St::Domain;
        type Kind = St::Kind;
        type Status = Set<members::status>;
        type Verified = St::Verified;
    }
    ///State transition - sets the `verified` field to Set
    pub struct SetVerified<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetVerified<St> {}
    impl<St: State> State for SetVerified<St> {
        type Domain = St::Domain;
        type Kind = St::Kind;
        type Status = St::Status;
        type Verified = Set<members::verified>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `domain` field
        pub struct domain(());
        ///Marker type for the `kind` field
        pub struct kind(());
        ///Marker type for the `status` field
        pub struct status(());
        ///Marker type for the `verified` field
        pub struct verified(());
    }
}

/// Builder for constructing an instance of this type.
pub struct SiteDomainBuilder<St: site_domain_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<SiteDomainKind<S>>,
        Option<SiteDomainStatus<S>>,
        Option<bool>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl SiteDomain<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> SiteDomainBuilder<site_domain_state::Empty, DefaultStr> {
        SiteDomainBuilder::new()
    }
}

impl<S: BosStr> SiteDomain<S> {
    /// Create a new builder for this type
    pub fn builder() -> SiteDomainBuilder<site_domain_state::Empty, S> {
        SiteDomainBuilder::builder()
    }
}

impl SiteDomainBuilder<site_domain_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        SiteDomainBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> SiteDomainBuilder<site_domain_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        SiteDomainBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> SiteDomainBuilder<St, S>
where
    St: site_domain_state::State,
    St::Domain: site_domain_state::IsUnset,
{
    /// Set the `domain` field (required)
    pub fn domain(
        mut self,
        value: impl Into<S>,
    ) -> SiteDomainBuilder<site_domain_state::SetDomain<St>, S> {
        self._fields.0 = Option::Some(value.into());
        SiteDomainBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> SiteDomainBuilder<St, S>
where
    St: site_domain_state::State,
    St::Kind: site_domain_state::IsUnset,
{
    /// Set the `kind` field (required)
    pub fn kind(
        mut self,
        value: impl Into<SiteDomainKind<S>>,
    ) -> SiteDomainBuilder<site_domain_state::SetKind<St>, S> {
        self._fields.1 = Option::Some(value.into());
        SiteDomainBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> SiteDomainBuilder<St, S>
where
    St: site_domain_state::State,
    St::Status: site_domain_state::IsUnset,
{
    /// Set the `status` field (required)
    pub fn status(
        mut self,
        value: impl Into<SiteDomainStatus<S>>,
    ) -> SiteDomainBuilder<site_domain_state::SetStatus<St>, S> {
        self._fields.2 = Option::Some(value.into());
        SiteDomainBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> SiteDomainBuilder<St, S>
where
    St: site_domain_state::State,
    St::Verified: site_domain_state::IsUnset,
{
    /// Set the `verified` field (required)
    pub fn verified(
        mut self,
        value: impl Into<bool>,
    ) -> SiteDomainBuilder<site_domain_state::SetVerified<St>, S> {
        self._fields.3 = Option::Some(value.into());
        SiteDomainBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> SiteDomainBuilder<St, S>
where
    St: site_domain_state::State,
    St::Domain: site_domain_state::IsSet,
    St::Kind: site_domain_state::IsSet,
    St::Status: site_domain_state::IsSet,
    St::Verified: site_domain_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> SiteDomain<S> {
        SiteDomain {
            domain: self._fields.0.unwrap(),
            kind: self._fields.1.unwrap(),
            status: self._fields.2.unwrap(),
            verified: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> SiteDomain<S> {
        SiteDomain {
            domain: self._fields.0.unwrap(),
            kind: self._fields.1.unwrap(),
            status: self._fields.2.unwrap(),
            verified: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_place_wisp_v2_site_getDomains() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("place.wisp.v2.site.getDomains"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: Some(
                        LexXrpcQueryParameter::Params(LexXrpcParameters {
                            required: Some(
                                vec![
                                    SmolStr::new_static("did"), SmolStr::new_static("rkey")
                                ],
                            ),
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = BTreeMap::new();
                                map.insert(
                                    SmolStr::new_static("did"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                );
                                map.insert(
                                    SmolStr::new_static("rkey"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::RecordKey),
                                        ..Default::default()
                                    }),
                                );
                                map
                            },
                            ..Default::default()
                        }),
                    ),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("siteDomain"),
                LexUserType::Object(LexObject {
                    required: Some(
                        vec![
                            SmolStr::new_static("domain"), SmolStr::new_static("kind"),
                            SmolStr::new_static("status"),
                            SmolStr::new_static("verified")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("domain"),
                            LexObjectProperty::String(LexString {
                                min_length: Some(3usize),
                                max_length: Some(253usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("kind"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("status"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("verified"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}