// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `place.wisp.v2` Lexicon namespace/module.
pub mod domain;
pub mod domains;
pub mod privateSite;
pub mod secret;
pub mod site;
pub mod wh;