[package]
name = "wisp-lexicons"
version = "0.1.0"
edition = "2024"

[features]
default = ["place_wisp"]
place_wisp = []

[dependencies]
jacquard-common = { git = "https://tangled.org/nonbinary.computer/jacquard" }
jacquard-derive = { git = "https://tangled.org/nonbinary.computer/jacquard" }
jacquard-lexicon = { git = "https://tangled.org/nonbinary.computer/jacquard" }
serde = { version = "1.0", features = ["derive"] }
rustversion = "1.0"
