// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.privateSite.create
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::bytes::Bytes;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Datetime, RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Create {
    pub body: Bytes,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct CreateOutput<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    /// Absent when the site never expires.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Datetime>,
    pub file_count: i64,
    /// Display name. Not an identifier.
    pub name: S,
    /// Stable identifier for this private site. Record-key syntax so it can become a permissioned-space key in v2.
    pub site_id: RecordKey<Rkey<S>>,
    pub total_bytes: i64,
    /// Owner-facing URL. Requires an authenticated session.
    pub url: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum CreateError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "PayloadTooLarge")]
    PayloadTooLarge(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for CreateError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::PayloadTooLarge(msg) => {
                write!(f, "PayloadTooLarge")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.privateSite.create` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `CreateOutput<S>` for this endpoint.*/
pub struct CreateResponse;
impl jacquard_common::xrpc::XrpcResp for CreateResponse {
    const NSID: &'static str = "place.wisp.v2.privateSite.create";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = CreateOutput<S>;
    type Err = CreateError;
}

impl jacquard_common::xrpc::XrpcRequest for Create {
    const NSID: &'static str = "place.wisp.v2.privateSite.create";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "multipart/form-data",
    );
    type Response = CreateResponse;
    fn encode_body(
        &self,
        buffer: &mut Vec<u8>,
    ) -> Result<(), jacquard_common::xrpc::EncodeError>
    where
        Self: Serialize,
    {
        Ok(buffer.extend_from_slice(self.body.as_ref()))
    }
    fn decode_body<'de>(
        body: &'de [u8],
    ) -> Result<Self, jacquard_common::error::DecodeError>
    where
        Self: Deserialize<'de>,
    {
        Ok(Self {
            body: jacquard_common::deps::bytes::Bytes::copy_from_slice(body),
        })
    }
}

/** Endpoint marker for the `place.wisp.v2.privateSite.create` procedure.

Path: `/xrpc/place.wisp.v2.privateSite.create`. The request payload type is `Create`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct CreateRequest;
impl jacquard_common::xrpc::XrpcEndpoint for CreateRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.privateSite.create";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "multipart/form-data",
    );
    type Request<S: BosStr> = Create;
    type Response = CreateResponse;
}