// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.privateSite.listShares
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, Datetime, RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::place_wisp::v2::privateSite::list_shares;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListShares<S: BosStr = DefaultStr> {
    pub site_id: RecordKey<Rkey<S>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListSharesOutput<S: BosStr = DefaultStr> {
    pub shares: Vec<list_shares::Share<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum ListSharesError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "NotFound")]
    NotFound(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for ListSharesError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Share<S: BosStr = DefaultStr> {
    /// Set when this link is restricted to a single account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audience_did: Option<Did<S>>,
    pub created_at: Datetime,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Datetime>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<Datetime>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<Datetime>,
    pub share_id: S,
    pub status: ShareStatus<S>,
    /// Non-secret leading fragment, for identification only.
    pub token_prefix: S,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_share_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ShareStatus<S: BosStr = DefaultStr> {
    Active,
    Expired,
    Revoked,
    Other(S),
}

impl<S: BosStr> ShareStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Active => "active",
            Self::Expired => "expired",
            Self::Revoked => "revoked",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "active" => Self::Active,
            "expired" => Self::Expired,
            "revoked" => Self::Revoked,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for ShareStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for ShareStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for ShareStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for ShareStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for ShareStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for ShareStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = ShareStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            ShareStatus::Active => ShareStatus::Active,
            ShareStatus::Expired => ShareStatus::Expired,
            ShareStatus::Revoked => ShareStatus::Revoked,
            ShareStatus::Other(v) => ShareStatus::Other(v.into_static()),
        }
    }
}

/** Response marker for the `place.wisp.v2.privateSite.listShares` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ListSharesOutput<S>` for this endpoint.*/
pub struct ListSharesResponse;
impl jacquard_common::xrpc::XrpcResp for ListSharesResponse {
    const NSID: &'static str = "place.wisp.v2.privateSite.listShares";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ListSharesOutput<S>;
    type Err = ListSharesError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for ListShares<S> {
    const NSID: &'static str = "place.wisp.v2.privateSite.listShares";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListSharesResponse;
}

/** Endpoint marker for the `place.wisp.v2.privateSite.listShares` query.

Path: `/xrpc/place.wisp.v2.privateSite.listShares`. The request payload type is `ListShares<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct ListSharesRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListSharesRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.privateSite.listShares";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = ListShares<S>;
    type Response = ListSharesResponse;
}

impl<S: BosStr> LexiconSchema for Share<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.privateSite.listShares"
    }
    fn def_name() -> &'static str {
        "share"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_privateSite_listShares()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

pub mod list_shares_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type SiteId;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type SiteId = Unset;
    }
    ///State transition - sets the `site_id` field to Set
    pub struct SetSiteId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSiteId<St> {}
    impl<St: State> State for SetSiteId<St> {
        type SiteId = Set<members::site_id>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `site_id` field
        pub struct site_id(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ListSharesBuilder<St: list_shares_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<RecordKey<Rkey<S>>>,),
    _type: PhantomData<fn() -> S>,
}

impl ListShares<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ListSharesBuilder<list_shares_state::Empty, DefaultStr> {
        ListSharesBuilder::new()
    }
}

impl<S: BosStr> ListShares<S> {
    /// Create a new builder for this type
    pub fn builder() -> ListSharesBuilder<list_shares_state::Empty, S> {
        ListSharesBuilder::builder()
    }
}

impl ListSharesBuilder<list_shares_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ListSharesBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ListSharesBuilder<list_shares_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ListSharesBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ListSharesBuilder<St, S>
where
    St: list_shares_state::State,
    St::SiteId: list_shares_state::IsUnset,
{
    /// Set the `siteId` field (required)
    pub fn site_id(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> ListSharesBuilder<list_shares_state::SetSiteId<St>, S> {
        self._fields.0 = Option::Some(value.into());
        ListSharesBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ListSharesBuilder<St, S>
where
    St: list_shares_state::State,
    St::SiteId: list_shares_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> ListShares<S> {
        ListShares {
            site_id: self._fields.0.unwrap(),
        }
    }
}

fn deserialize_share_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}

pub mod share_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type ShareId;
        type Status;
        type TokenPrefix;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type ShareId = Unset;
        type Status = Unset;
        type TokenPrefix = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type ShareId = St::ShareId;
        type Status = St::Status;
        type TokenPrefix = St::TokenPrefix;
    }
    ///State transition - sets the `share_id` field to Set
    pub struct SetShareId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetShareId<St> {}
    impl<St: State> State for SetShareId<St> {
        type CreatedAt = St::CreatedAt;
        type ShareId = Set<members::share_id>;
        type Status = St::Status;
        type TokenPrefix = St::TokenPrefix;
    }
    ///State transition - sets the `status` field to Set
    pub struct SetStatus<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStatus<St> {}
    impl<St: State> State for SetStatus<St> {
        type CreatedAt = St::CreatedAt;
        type ShareId = St::ShareId;
        type Status = Set<members::status>;
        type TokenPrefix = St::TokenPrefix;
    }
    ///State transition - sets the `token_prefix` field to Set
    pub struct SetTokenPrefix<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTokenPrefix<St> {}
    impl<St: State> State for SetTokenPrefix<St> {
        type CreatedAt = St::CreatedAt;
        type ShareId = St::ShareId;
        type Status = St::Status;
        type TokenPrefix = Set<members::token_prefix>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `share_id` field
        pub struct share_id(());
        ///Marker type for the `status` field
        pub struct status(());
        ///Marker type for the `token_prefix` field
        pub struct token_prefix(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ShareBuilder<St: share_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Did<S>>,
        Option<Datetime>,
        Option<Datetime>,
        Option<S>,
        Option<Datetime>,
        Option<Datetime>,
        Option<S>,
        Option<ShareStatus<S>>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Share<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ShareBuilder<share_state::Empty, DefaultStr> {
        ShareBuilder::new()
    }
}

impl<S: BosStr> Share<S> {
    /// Create a new builder for this type
    pub fn builder() -> ShareBuilder<share_state::Empty, S> {
        ShareBuilder::builder()
    }
}

impl ShareBuilder<share_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ShareBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ShareBuilder<share_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ShareBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: share_state::State, S: BosStr> ShareBuilder<St, S> {
    /// Set the `audienceDid` field (optional)
    pub fn audience_did(mut self, value: impl Into<Option<Did<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `audienceDid` field to an Option value (optional)
    pub fn maybe_audience_did(mut self, value: Option<Did<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> ShareBuilder<St, S>
where
    St: share_state::State,
    St::CreatedAt: share_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> ShareBuilder<share_state::SetCreatedAt<St>, S> {
        self._fields.1 = Option::Some(value.into());
        ShareBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: share_state::State, S: BosStr> ShareBuilder<St, S> {
    /// Set the `expiresAt` field (optional)
    pub fn expires_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `expiresAt` field to an Option value (optional)
    pub fn maybe_expires_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: share_state::State, S: BosStr> ShareBuilder<St, S> {
    /// Set the `label` field (optional)
    pub fn label(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `label` field to an Option value (optional)
    pub fn maybe_label(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: share_state::State, S: BosStr> ShareBuilder<St, S> {
    /// Set the `lastUsedAt` field (optional)
    pub fn last_used_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `lastUsedAt` field to an Option value (optional)
    pub fn maybe_last_used_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: share_state::State, S: BosStr> ShareBuilder<St, S> {
    /// Set the `revokedAt` field (optional)
    pub fn revoked_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `revokedAt` field to an Option value (optional)
    pub fn maybe_revoked_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St, S: BosStr> ShareBuilder<St, S>
where
    St: share_state::State,
    St::ShareId: share_state::IsUnset,
{
    /// Set the `shareId` field (required)
    pub fn share_id(
        mut self,
        value: impl Into<S>,
    ) -> ShareBuilder<share_state::SetShareId<St>, S> {
        self._fields.6 = Option::Some(value.into());
        ShareBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ShareBuilder<St, S>
where
    St: share_state::State,
    St::Status: share_state::IsUnset,
{
    /// Set the `status` field (required)
    pub fn status(
        mut self,
        value: impl Into<ShareStatus<S>>,
    ) -> ShareBuilder<share_state::SetStatus<St>, S> {
        self._fields.7 = Option::Some(value.into());
        ShareBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ShareBuilder<St, S>
where
    St: share_state::State,
    St::TokenPrefix: share_state::IsUnset,
{
    /// Set the `tokenPrefix` field (required)
    pub fn token_prefix(
        mut self,
        value: impl Into<S>,
    ) -> ShareBuilder<share_state::SetTokenPrefix<St>, S> {
        self._fields.8 = Option::Some(value.into());
        ShareBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ShareBuilder<St, S>
where
    St: share_state::State,
    St::CreatedAt: share_state::IsSet,
    St::ShareId: share_state::IsSet,
    St::Status: share_state::IsSet,
    St::TokenPrefix: share_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Share<S> {
        Share {
            audience_did: self._fields.0,
            created_at: self._fields.1.unwrap(),
            expires_at: self._fields.2,
            label: self._fields.3,
            last_used_at: self._fields.4,
            revoked_at: self._fields.5,
            share_id: self._fields.6.unwrap(),
            status: self._fields.7.unwrap(),
            token_prefix: self._fields.8.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Share<S> {
        Share {
            audience_did: self._fields.0,
            created_at: self._fields.1.unwrap(),
            expires_at: self._fields.2,
            label: self._fields.3,
            last_used_at: self._fields.4,
            revoked_at: self._fields.5,
            share_id: self._fields.6.unwrap(),
            status: self._fields.7.unwrap(),
            token_prefix: self._fields.8.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_place_wisp_v2_privateSite_listShares() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("place.wisp.v2.privateSite.listShares"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: Some(
                        LexXrpcQueryParameter::Params(LexXrpcParameters {
                            required: Some(vec![SmolStr::new_static("siteId")]),
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = BTreeMap::new();
                                map.insert(
                                    SmolStr::new_static("siteId"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::RecordKey),
                                        ..Default::default()
                                    }),
                                );
                                map
                            },
                            ..Default::default()
                        }),
                    ),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("share"),
                LexUserType::Object(LexObject {
                    required: Some(
                        vec![
                            SmolStr::new_static("shareId"),
                            SmolStr::new_static("tokenPrefix"),
                            SmolStr::new_static("createdAt"),
                            SmolStr::new_static("status")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("audienceDid"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Set when this link is restricted to a single account.",
                                    ),
                                ),
                                format: Some(LexStringFormat::Did),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("createdAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("expiresAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("label"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("lastUsedAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("revokedAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("shareId"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("status"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("tokenPrefix"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Non-secret leading fragment, for identification only.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}