// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.privateSite.list
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Datetime, RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::place_wisp::v2::privateSite::list;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListOutput<S: BosStr = DefaultStr> {
    pub sites: Vec<list::PrivateSiteSummary<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum ListError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for ListError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct PrivateSiteSummary<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    pub expired: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Datetime>,
    pub file_count: i64,
    pub name: S,
    /// Number of share links that currently grant access.
    pub share_count: i64,
    pub site_id: RecordKey<Rkey<S>>,
    pub total_bytes: i64,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_private_site_summary_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Request marker for the `place.wisp.v2.privateSite.list` query.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct List;
/** Response marker for the `place.wisp.v2.privateSite.list` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ListOutput<S>` for this endpoint.*/
pub struct ListResponse;
impl jacquard_common::xrpc::XrpcResp for ListResponse {
    const NSID: &'static str = "place.wisp.v2.privateSite.list";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ListOutput<S>;
    type Err = ListError;
}

impl jacquard_common::xrpc::XrpcRequest for List {
    const NSID: &'static str = "place.wisp.v2.privateSite.list";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListResponse;
    fn encode_body(
        &self,
        _buffer: &mut Vec<u8>,
    ) -> Result<(), jacquard_common::xrpc::EncodeError> {
        Ok(())
    }
}

/** Endpoint marker for the `place.wisp.v2.privateSite.list` query.

Path: `/xrpc/place.wisp.v2.privateSite.list`. The request payload type is `List`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct ListRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.privateSite.list";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = List;
    type Response = ListResponse;
}

impl<S: BosStr> LexiconSchema for PrivateSiteSummary<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.privateSite.list"
    }
    fn def_name() -> &'static str {
        "privateSiteSummary"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_privateSite_list()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn deserialize_private_site_summary_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}

pub mod private_site_summary_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Expired;
        type FileCount;
        type Name;
        type ShareCount;
        type SiteId;
        type TotalBytes;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Expired = Unset;
        type FileCount = Unset;
        type Name = Unset;
        type ShareCount = Unset;
        type SiteId = Unset;
        type TotalBytes = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Expired = St::Expired;
        type FileCount = St::FileCount;
        type Name = St::Name;
        type ShareCount = St::ShareCount;
        type SiteId = St::SiteId;
        type TotalBytes = St::TotalBytes;
    }
    ///State transition - sets the `expired` field to Set
    pub struct SetExpired<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetExpired<St> {}
    impl<St: State> State for SetExpired<St> {
        type CreatedAt = St::CreatedAt;
        type Expired = Set<members::expired>;
        type FileCount = St::FileCount;
        type Name = St::Name;
        type ShareCount = St::ShareCount;
        type SiteId = St::SiteId;
        type TotalBytes = St::TotalBytes;
    }
    ///State transition - sets the `file_count` field to Set
    pub struct SetFileCount<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetFileCount<St> {}
    impl<St: State> State for SetFileCount<St> {
        type CreatedAt = St::CreatedAt;
        type Expired = St::Expired;
        type FileCount = Set<members::file_count>;
        type Name = St::Name;
        type ShareCount = St::ShareCount;
        type SiteId = St::SiteId;
        type TotalBytes = St::TotalBytes;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type CreatedAt = St::CreatedAt;
        type Expired = St::Expired;
        type FileCount = St::FileCount;
        type Name = Set<members::name>;
        type ShareCount = St::ShareCount;
        type SiteId = St::SiteId;
        type TotalBytes = St::TotalBytes;
    }
    ///State transition - sets the `share_count` field to Set
    pub struct SetShareCount<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetShareCount<St> {}
    impl<St: State> State for SetShareCount<St> {
        type CreatedAt = St::CreatedAt;
        type Expired = St::Expired;
        type FileCount = St::FileCount;
        type Name = St::Name;
        type ShareCount = Set<members::share_count>;
        type SiteId = St::SiteId;
        type TotalBytes = St::TotalBytes;
    }
    ///State transition - sets the `site_id` field to Set
    pub struct SetSiteId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSiteId<St> {}
    impl<St: State> State for SetSiteId<St> {
        type CreatedAt = St::CreatedAt;
        type Expired = St::Expired;
        type FileCount = St::FileCount;
        type Name = St::Name;
        type ShareCount = St::ShareCount;
        type SiteId = Set<members::site_id>;
        type TotalBytes = St::TotalBytes;
    }
    ///State transition - sets the `total_bytes` field to Set
    pub struct SetTotalBytes<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTotalBytes<St> {}
    impl<St: State> State for SetTotalBytes<St> {
        type CreatedAt = St::CreatedAt;
        type Expired = St::Expired;
        type FileCount = St::FileCount;
        type Name = St::Name;
        type ShareCount = St::ShareCount;
        type SiteId = St::SiteId;
        type TotalBytes = Set<members::total_bytes>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `expired` field
        pub struct expired(());
        ///Marker type for the `file_count` field
        pub struct file_count(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `share_count` field
        pub struct share_count(());
        ///Marker type for the `site_id` field
        pub struct site_id(());
        ///Marker type for the `total_bytes` field
        pub struct total_bytes(());
    }
}

/// Builder for constructing an instance of this type.
pub struct PrivateSiteSummaryBuilder<
    St: private_site_summary_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<bool>,
        Option<Datetime>,
        Option<i64>,
        Option<S>,
        Option<i64>,
        Option<RecordKey<Rkey<S>>>,
        Option<i64>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl PrivateSiteSummary<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> PrivateSiteSummaryBuilder<
        private_site_summary_state::Empty,
        DefaultStr,
    > {
        PrivateSiteSummaryBuilder::new()
    }
}

impl<S: BosStr> PrivateSiteSummary<S> {
    /// Create a new builder for this type
    pub fn builder() -> PrivateSiteSummaryBuilder<private_site_summary_state::Empty, S> {
        PrivateSiteSummaryBuilder::builder()
    }
}

impl PrivateSiteSummaryBuilder<private_site_summary_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> PrivateSiteSummaryBuilder<private_site_summary_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::CreatedAt: private_site_summary_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> PrivateSiteSummaryBuilder<private_site_summary_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::Expired: private_site_summary_state::IsUnset,
{
    /// Set the `expired` field (required)
    pub fn expired(
        mut self,
        value: impl Into<bool>,
    ) -> PrivateSiteSummaryBuilder<private_site_summary_state::SetExpired<St>, S> {
        self._fields.1 = Option::Some(value.into());
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: private_site_summary_state::State, S: BosStr> PrivateSiteSummaryBuilder<St, S> {
    /// Set the `expiresAt` field (optional)
    pub fn expires_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `expiresAt` field to an Option value (optional)
    pub fn maybe_expires_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::FileCount: private_site_summary_state::IsUnset,
{
    /// Set the `fileCount` field (required)
    pub fn file_count(
        mut self,
        value: impl Into<i64>,
    ) -> PrivateSiteSummaryBuilder<private_site_summary_state::SetFileCount<St>, S> {
        self._fields.3 = Option::Some(value.into());
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::Name: private_site_summary_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<S>,
    ) -> PrivateSiteSummaryBuilder<private_site_summary_state::SetName<St>, S> {
        self._fields.4 = Option::Some(value.into());
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::ShareCount: private_site_summary_state::IsUnset,
{
    /// Set the `shareCount` field (required)
    pub fn share_count(
        mut self,
        value: impl Into<i64>,
    ) -> PrivateSiteSummaryBuilder<private_site_summary_state::SetShareCount<St>, S> {
        self._fields.5 = Option::Some(value.into());
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::SiteId: private_site_summary_state::IsUnset,
{
    /// Set the `siteId` field (required)
    pub fn site_id(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> PrivateSiteSummaryBuilder<private_site_summary_state::SetSiteId<St>, S> {
        self._fields.6 = Option::Some(value.into());
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::TotalBytes: private_site_summary_state::IsUnset,
{
    /// Set the `totalBytes` field (required)
    pub fn total_bytes(
        mut self,
        value: impl Into<i64>,
    ) -> PrivateSiteSummaryBuilder<private_site_summary_state::SetTotalBytes<St>, S> {
        self._fields.7 = Option::Some(value.into());
        PrivateSiteSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PrivateSiteSummaryBuilder<St, S>
where
    St: private_site_summary_state::State,
    St::CreatedAt: private_site_summary_state::IsSet,
    St::Expired: private_site_summary_state::IsSet,
    St::FileCount: private_site_summary_state::IsSet,
    St::Name: private_site_summary_state::IsSet,
    St::ShareCount: private_site_summary_state::IsSet,
    St::SiteId: private_site_summary_state::IsSet,
    St::TotalBytes: private_site_summary_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> PrivateSiteSummary<S> {
        PrivateSiteSummary {
            created_at: self._fields.0.unwrap(),
            expired: self._fields.1.unwrap(),
            expires_at: self._fields.2,
            file_count: self._fields.3.unwrap(),
            name: self._fields.4.unwrap(),
            share_count: self._fields.5.unwrap(),
            site_id: self._fields.6.unwrap(),
            total_bytes: self._fields.7.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> PrivateSiteSummary<S> {
        PrivateSiteSummary {
            created_at: self._fields.0.unwrap(),
            expired: self._fields.1.unwrap(),
            expires_at: self._fields.2,
            file_count: self._fields.3.unwrap(),
            name: self._fields.4.unwrap(),
            share_count: self._fields.5.unwrap(),
            site_id: self._fields.6.unwrap(),
            total_bytes: self._fields.7.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_place_wisp_v2_privateSite_list() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("place.wisp.v2.privateSite.list"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: None,
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("privateSiteSummary"),
                LexUserType::Object(LexObject {
                    required: Some(
                        vec![
                            SmolStr::new_static("siteId"), SmolStr::new_static("name"),
                            SmolStr::new_static("fileCount"),
                            SmolStr::new_static("totalBytes"),
                            SmolStr::new_static("createdAt"),
                            SmolStr::new_static("shareCount"),
                            SmolStr::new_static("expired")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("createdAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("expired"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("expiresAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("fileCount"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("name"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("shareCount"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("siteId"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::RecordKey),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("totalBytes"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}