// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.privateSite.revokeShare
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct RevokeShare<S: BosStr = DefaultStr> {
    pub share_id: S,
    pub site_id: RecordKey<Rkey<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct RevokeShareOutput<S: BosStr = DefaultStr> {
    pub revoked: bool,
    pub share_id: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum RevokeShareError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "NotFound")]
    NotFound(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for RevokeShareError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.privateSite.revokeShare` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `RevokeShareOutput<S>` for this endpoint.*/
pub struct RevokeShareResponse;
impl jacquard_common::xrpc::XrpcResp for RevokeShareResponse {
    const NSID: &'static str = "place.wisp.v2.privateSite.revokeShare";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = RevokeShareOutput<S>;
    type Err = RevokeShareError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for RevokeShare<S> {
    const NSID: &'static str = "place.wisp.v2.privateSite.revokeShare";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RevokeShareResponse;
}

/** Endpoint marker for the `place.wisp.v2.privateSite.revokeShare` procedure.

Path: `/xrpc/place.wisp.v2.privateSite.revokeShare`. The request payload type is `RevokeShare<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct RevokeShareRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RevokeShareRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.privateSite.revokeShare";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = RevokeShare<S>;
    type Response = RevokeShareResponse;
}

pub mod revoke_share_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type ShareId;
        type SiteId;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type ShareId = Unset;
        type SiteId = Unset;
    }
    ///State transition - sets the `share_id` field to Set
    pub struct SetShareId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetShareId<St> {}
    impl<St: State> State for SetShareId<St> {
        type ShareId = Set<members::share_id>;
        type SiteId = St::SiteId;
    }
    ///State transition - sets the `site_id` field to Set
    pub struct SetSiteId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSiteId<St> {}
    impl<St: State> State for SetSiteId<St> {
        type ShareId = St::ShareId;
        type SiteId = Set<members::site_id>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `share_id` field
        pub struct share_id(());
        ///Marker type for the `site_id` field
        pub struct site_id(());
    }
}

/// Builder for constructing an instance of this type.
pub struct RevokeShareBuilder<St: revoke_share_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<RecordKey<Rkey<S>>>),
    _type: PhantomData<fn() -> S>,
}

impl RevokeShare<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> RevokeShareBuilder<revoke_share_state::Empty, DefaultStr> {
        RevokeShareBuilder::new()
    }
}

impl<S: BosStr> RevokeShare<S> {
    /// Create a new builder for this type
    pub fn builder() -> RevokeShareBuilder<revoke_share_state::Empty, S> {
        RevokeShareBuilder::builder()
    }
}

impl RevokeShareBuilder<revoke_share_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        RevokeShareBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> RevokeShareBuilder<revoke_share_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        RevokeShareBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RevokeShareBuilder<St, S>
where
    St: revoke_share_state::State,
    St::ShareId: revoke_share_state::IsUnset,
{
    /// Set the `shareId` field (required)
    pub fn share_id(
        mut self,
        value: impl Into<S>,
    ) -> RevokeShareBuilder<revoke_share_state::SetShareId<St>, S> {
        self._fields.0 = Option::Some(value.into());
        RevokeShareBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RevokeShareBuilder<St, S>
where
    St: revoke_share_state::State,
    St::SiteId: revoke_share_state::IsUnset,
{
    /// Set the `siteId` field (required)
    pub fn site_id(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> RevokeShareBuilder<revoke_share_state::SetSiteId<St>, S> {
        self._fields.1 = Option::Some(value.into());
        RevokeShareBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RevokeShareBuilder<St, S>
where
    St: revoke_share_state::State,
    St::ShareId: revoke_share_state::IsSet,
    St::SiteId: revoke_share_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> RevokeShare<S> {
        RevokeShare {
            share_id: self._fields.0.unwrap(),
            site_id: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> RevokeShare<S> {
        RevokeShare {
            share_id: self._fields.0.unwrap(),
            site_id: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}