// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.domain.claimSubdomain
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ClaimSubdomain<S: BosStr = DefaultStr> {
    /// Subdomain label only (for example, alice).
    pub handle: S,
    /// Optional place.wisp.fs rkey to map immediately after claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site_rkey: Option<RecordKey<Rkey<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ClaimSubdomainOutput<S: BosStr = DefaultStr> {
    pub domain: S,
    pub kind: ClaimSubdomainOutputKind<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site_rkey: Option<RecordKey<Rkey<S>>>,
    pub status: ClaimSubdomainOutputStatus<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ClaimSubdomainOutputKind<S: BosStr = DefaultStr> {
    Wisp,
    Other(S),
}

impl<S: BosStr> ClaimSubdomainOutputKind<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Wisp => "wisp",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "wisp" => Self::Wisp,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for ClaimSubdomainOutputKind<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for ClaimSubdomainOutputKind<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for ClaimSubdomainOutputKind<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de>
for ClaimSubdomainOutputKind<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for ClaimSubdomainOutputKind<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for ClaimSubdomainOutputKind<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = ClaimSubdomainOutputKind<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            ClaimSubdomainOutputKind::Wisp => ClaimSubdomainOutputKind::Wisp,
            ClaimSubdomainOutputKind::Other(v) => {
                ClaimSubdomainOutputKind::Other(v.into_static())
            }
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ClaimSubdomainOutputStatus<S: BosStr = DefaultStr> {
    Verified,
    AlreadyClaimed,
    Other(S),
}

impl<S: BosStr> ClaimSubdomainOutputStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Verified => "verified",
            Self::AlreadyClaimed => "alreadyClaimed",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "verified" => Self::Verified,
            "alreadyClaimed" => Self::AlreadyClaimed,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for ClaimSubdomainOutputStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for ClaimSubdomainOutputStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for ClaimSubdomainOutputStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de>
for ClaimSubdomainOutputStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for ClaimSubdomainOutputStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for ClaimSubdomainOutputStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = ClaimSubdomainOutputStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            ClaimSubdomainOutputStatus::Verified => ClaimSubdomainOutputStatus::Verified,
            ClaimSubdomainOutputStatus::AlreadyClaimed => {
                ClaimSubdomainOutputStatus::AlreadyClaimed
            }
            ClaimSubdomainOutputStatus::Other(v) => {
                ClaimSubdomainOutputStatus::Other(v.into_static())
            }
        }
    }
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum ClaimSubdomainError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidDomain")]
    InvalidDomain(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "AlreadyClaimed")]
    AlreadyClaimed(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "DomainLimitReached")]
    DomainLimitReached(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "RateLimitExceeded")]
    RateLimitExceeded(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for ClaimSubdomainError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidDomain(msg) => {
                write!(f, "InvalidDomain")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AlreadyClaimed(msg) => {
                write!(f, "AlreadyClaimed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::DomainLimitReached(msg) => {
                write!(f, "DomainLimitReached")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::RateLimitExceeded(msg) => {
                write!(f, "RateLimitExceeded")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.domain.claimSubdomain` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ClaimSubdomainOutput<S>` for this endpoint.*/
pub struct ClaimSubdomainResponse;
impl jacquard_common::xrpc::XrpcResp for ClaimSubdomainResponse {
    const NSID: &'static str = "place.wisp.v2.domain.claimSubdomain";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ClaimSubdomainOutput<S>;
    type Err = ClaimSubdomainError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for ClaimSubdomain<S> {
    const NSID: &'static str = "place.wisp.v2.domain.claimSubdomain";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = ClaimSubdomainResponse;
}

/** Endpoint marker for the `place.wisp.v2.domain.claimSubdomain` procedure.

Path: `/xrpc/place.wisp.v2.domain.claimSubdomain`. The request payload type is `ClaimSubdomain<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct ClaimSubdomainRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ClaimSubdomainRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.domain.claimSubdomain";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = ClaimSubdomain<S>;
    type Response = ClaimSubdomainResponse;
}