// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.domain.claim
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Claim<S: BosStr = DefaultStr> {
    /// Custom domain FQDN to claim (for example, example.com).
    pub domain: S,
    /// Optional place.wisp.fs rkey to map immediately after claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site_rkey: Option<RecordKey<Rkey<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ClaimOutput<S: BosStr = DefaultStr> {
    /// Identifier used to construct DNS challenge targets for custom domains.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge_id: Option<S>,
    /// Advisory CNAME target (custom domains).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cname_target: Option<S>,
    pub domain: S,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<ClaimOutputKind<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site_rkey: Option<RecordKey<Rkey<S>>>,
    pub status: ClaimOutputStatus<S>,
    /// TXT hostname to set for ownership proof (custom domains).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub txt_name: Option<S>,
    /// TXT value to set for ownership proof (custom domains).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub txt_value: Option<Did<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ClaimOutputKind<S: BosStr = DefaultStr> {
    Custom,
    Other(S),
}

impl<S: BosStr> ClaimOutputKind<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Custom => "custom",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "custom" => Self::Custom,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for ClaimOutputKind<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for ClaimOutputKind<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for ClaimOutputKind<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for ClaimOutputKind<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for ClaimOutputKind<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for ClaimOutputKind<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = ClaimOutputKind<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            ClaimOutputKind::Custom => ClaimOutputKind::Custom,
            ClaimOutputKind::Other(v) => ClaimOutputKind::Other(v.into_static()),
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ClaimOutputStatus<S: BosStr = DefaultStr> {
    AlreadyClaimed,
    PendingVerification,
    Verified,
    Other(S),
}

impl<S: BosStr> ClaimOutputStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::AlreadyClaimed => "alreadyClaimed",
            Self::PendingVerification => "pendingVerification",
            Self::Verified => "verified",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "alreadyClaimed" => Self::AlreadyClaimed,
            "pendingVerification" => Self::PendingVerification,
            "verified" => Self::Verified,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for ClaimOutputStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for ClaimOutputStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for ClaimOutputStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for ClaimOutputStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for ClaimOutputStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for ClaimOutputStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = ClaimOutputStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            ClaimOutputStatus::AlreadyClaimed => ClaimOutputStatus::AlreadyClaimed,
            ClaimOutputStatus::PendingVerification => {
                ClaimOutputStatus::PendingVerification
            }
            ClaimOutputStatus::Verified => ClaimOutputStatus::Verified,
            ClaimOutputStatus::Other(v) => ClaimOutputStatus::Other(v.into_static()),
        }
    }
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum ClaimError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidDomain")]
    InvalidDomain(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "AlreadyClaimed")]
    AlreadyClaimed(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "DomainLimitReached")]
    DomainLimitReached(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "RateLimitExceeded")]
    RateLimitExceeded(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for ClaimError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidDomain(msg) => {
                write!(f, "InvalidDomain")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AlreadyClaimed(msg) => {
                write!(f, "AlreadyClaimed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::DomainLimitReached(msg) => {
                write!(f, "DomainLimitReached")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::RateLimitExceeded(msg) => {
                write!(f, "RateLimitExceeded")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.domain.claim` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ClaimOutput<S>` for this endpoint.*/
pub struct ClaimResponse;
impl jacquard_common::xrpc::XrpcResp for ClaimResponse {
    const NSID: &'static str = "place.wisp.v2.domain.claim";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ClaimOutput<S>;
    type Err = ClaimError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for Claim<S> {
    const NSID: &'static str = "place.wisp.v2.domain.claim";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = ClaimResponse;
}

/** Endpoint marker for the `place.wisp.v2.domain.claim` procedure.

Path: `/xrpc/place.wisp.v2.domain.claim`. The request payload type is `Claim<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct ClaimRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ClaimRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.domain.claim";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = Claim<S>;
    type Response = ClaimResponse;
}