// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.domain.delete
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Delete<S: BosStr = DefaultStr> {
    /// Fully-qualified domain to delete (wisp subdomain or custom domain).
    pub domain: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct DeleteOutput<S: BosStr = DefaultStr> {
    pub deleted: bool,
    pub domain: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum DeleteError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidDomain")]
    InvalidDomain(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "NotFound")]
    NotFound(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for DeleteError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidDomain(msg) => {
                write!(f, "InvalidDomain")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.domain.delete` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `DeleteOutput<S>` for this endpoint.*/
pub struct DeleteResponse;
impl jacquard_common::xrpc::XrpcResp for DeleteResponse {
    const NSID: &'static str = "place.wisp.v2.domain.delete";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = DeleteOutput<S>;
    type Err = DeleteError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for Delete<S> {
    const NSID: &'static str = "place.wisp.v2.domain.delete";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = DeleteResponse;
}

/** Endpoint marker for the `place.wisp.v2.domain.delete` procedure.

Path: `/xrpc/place.wisp.v2.domain.delete`. The request payload type is `Delete<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct DeleteRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DeleteRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.domain.delete";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = Delete<S>;
    type Response = DeleteResponse;
}