// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.domain.getList
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Datetime, RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::place_wisp::v2::domain::get_list;
/// Summary of a claimed domain for list views.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct DomainSummary<S: BosStr = DefaultStr> {
    pub domain: S,
    pub kind: DomainSummaryKind<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_checked_at: Option<Datetime>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site_rkey: Option<RecordKey<Rkey<S>>>,
    pub status: DomainSummaryStatus<S>,
    pub verified: bool,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_domain_summary_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DomainSummaryKind<S: BosStr = DefaultStr> {
    Wisp,
    Custom,
    Other(S),
}

impl<S: BosStr> DomainSummaryKind<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Wisp => "wisp",
            Self::Custom => "custom",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "wisp" => Self::Wisp,
            "custom" => Self::Custom,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for DomainSummaryKind<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for DomainSummaryKind<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for DomainSummaryKind<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for DomainSummaryKind<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for DomainSummaryKind<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for DomainSummaryKind<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = DomainSummaryKind<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            DomainSummaryKind::Wisp => DomainSummaryKind::Wisp,
            DomainSummaryKind::Custom => DomainSummaryKind::Custom,
            DomainSummaryKind::Other(v) => DomainSummaryKind::Other(v.into_static()),
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DomainSummaryStatus<S: BosStr = DefaultStr> {
    PendingVerification,
    Verified,
    Other(S),
}

impl<S: BosStr> DomainSummaryStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::PendingVerification => "pendingVerification",
            Self::Verified => "verified",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "pendingVerification" => Self::PendingVerification,
            "verified" => Self::Verified,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for DomainSummaryStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for DomainSummaryStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for DomainSummaryStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for DomainSummaryStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for DomainSummaryStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for DomainSummaryStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = DomainSummaryStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            DomainSummaryStatus::PendingVerification => {
                DomainSummaryStatus::PendingVerification
            }
            DomainSummaryStatus::Verified => DomainSummaryStatus::Verified,
            DomainSummaryStatus::Other(v) => DomainSummaryStatus::Other(v.into_static()),
        }
    }
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetListOutput<S: BosStr = DefaultStr> {
    /// Domains owned by the caller DID.
    pub domains: Vec<get_list::DomainSummary<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum GetListError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for GetListError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

impl<S: BosStr> LexiconSchema for DomainSummary<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.domain.getList"
    }
    fn def_name() -> &'static str {
        "domainSummary"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_domain_getList()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.domain;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 253usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("domain"),
                    max: 253usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.domain;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 3usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("domain"),
                    min: 3usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

/** Request marker for the `place.wisp.v2.domain.getList` query.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct GetList;
/** Response marker for the `place.wisp.v2.domain.getList` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetListOutput<S>` for this endpoint.*/
pub struct GetListResponse;
impl jacquard_common::xrpc::XrpcResp for GetListResponse {
    const NSID: &'static str = "place.wisp.v2.domain.getList";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetListOutput<S>;
    type Err = GetListError;
}

impl jacquard_common::xrpc::XrpcRequest for GetList {
    const NSID: &'static str = "place.wisp.v2.domain.getList";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetListResponse;
    fn encode_body(
        &self,
        _buffer: &mut Vec<u8>,
    ) -> Result<(), jacquard_common::xrpc::EncodeError> {
        Ok(())
    }
}

/** Endpoint marker for the `place.wisp.v2.domain.getList` query.

Path: `/xrpc/place.wisp.v2.domain.getList`. The request payload type is `GetList`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct GetListRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetListRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.domain.getList";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetList;
    type Response = GetListResponse;
}

fn deserialize_domain_summary_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}

pub mod domain_summary_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Domain;
        type Kind;
        type Status;
        type Verified;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Domain = Unset;
        type Kind = Unset;
        type Status = Unset;
        type Verified = Unset;
    }
    ///State transition - sets the `domain` field to Set
    pub struct SetDomain<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDomain<St> {}
    impl<St: State> State for SetDomain<St> {
        type Domain = Set<members::domain>;
        type Kind = St::Kind;
        type Status = St::Status;
        type Verified = St::Verified;
    }
    ///State transition - sets the `kind` field to Set
    pub struct SetKind<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetKind<St> {}
    impl<St: State> State for SetKind<St> {
        type Domain = St::Domain;
        type Kind = Set<members::kind>;
        type Status = St::Status;
        type Verified = St::Verified;
    }
    ///State transition - sets the `status` field to Set
    pub struct SetStatus<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStatus<St> {}
    impl<St: State> State for SetStatus<St> {
        type Domain = St::Domain;
        type Kind = St::Kind;
        type Status = Set<members::status>;
        type Verified = St::Verified;
    }
    ///State transition - sets the `verified` field to Set
    pub struct SetVerified<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetVerified<St> {}
    impl<St: State> State for SetVerified<St> {
        type Domain = St::Domain;
        type Kind = St::Kind;
        type Status = St::Status;
        type Verified = Set<members::verified>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `domain` field
        pub struct domain(());
        ///Marker type for the `kind` field
        pub struct kind(());
        ///Marker type for the `status` field
        pub struct status(());
        ///Marker type for the `verified` field
        pub struct verified(());
    }
}

/// Builder for constructing an instance of this type.
pub struct DomainSummaryBuilder<
    St: domain_summary_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<DomainSummaryKind<S>>,
        Option<Datetime>,
        Option<RecordKey<Rkey<S>>>,
        Option<DomainSummaryStatus<S>>,
        Option<bool>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl DomainSummary<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> DomainSummaryBuilder<domain_summary_state::Empty, DefaultStr> {
        DomainSummaryBuilder::new()
    }
}

impl<S: BosStr> DomainSummary<S> {
    /// Create a new builder for this type
    pub fn builder() -> DomainSummaryBuilder<domain_summary_state::Empty, S> {
        DomainSummaryBuilder::builder()
    }
}

impl DomainSummaryBuilder<domain_summary_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        DomainSummaryBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> DomainSummaryBuilder<domain_summary_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        DomainSummaryBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainSummaryBuilder<St, S>
where
    St: domain_summary_state::State,
    St::Domain: domain_summary_state::IsUnset,
{
    /// Set the `domain` field (required)
    pub fn domain(
        mut self,
        value: impl Into<S>,
    ) -> DomainSummaryBuilder<domain_summary_state::SetDomain<St>, S> {
        self._fields.0 = Option::Some(value.into());
        DomainSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainSummaryBuilder<St, S>
where
    St: domain_summary_state::State,
    St::Kind: domain_summary_state::IsUnset,
{
    /// Set the `kind` field (required)
    pub fn kind(
        mut self,
        value: impl Into<DomainSummaryKind<S>>,
    ) -> DomainSummaryBuilder<domain_summary_state::SetKind<St>, S> {
        self._fields.1 = Option::Some(value.into());
        DomainSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: domain_summary_state::State, S: BosStr> DomainSummaryBuilder<St, S> {
    /// Set the `lastCheckedAt` field (optional)
    pub fn last_checked_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `lastCheckedAt` field to an Option value (optional)
    pub fn maybe_last_checked_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: domain_summary_state::State, S: BosStr> DomainSummaryBuilder<St, S> {
    /// Set the `siteRkey` field (optional)
    pub fn site_rkey(mut self, value: impl Into<Option<RecordKey<Rkey<S>>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `siteRkey` field to an Option value (optional)
    pub fn maybe_site_rkey(mut self, value: Option<RecordKey<Rkey<S>>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St, S: BosStr> DomainSummaryBuilder<St, S>
where
    St: domain_summary_state::State,
    St::Status: domain_summary_state::IsUnset,
{
    /// Set the `status` field (required)
    pub fn status(
        mut self,
        value: impl Into<DomainSummaryStatus<S>>,
    ) -> DomainSummaryBuilder<domain_summary_state::SetStatus<St>, S> {
        self._fields.4 = Option::Some(value.into());
        DomainSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainSummaryBuilder<St, S>
where
    St: domain_summary_state::State,
    St::Verified: domain_summary_state::IsUnset,
{
    /// Set the `verified` field (required)
    pub fn verified(
        mut self,
        value: impl Into<bool>,
    ) -> DomainSummaryBuilder<domain_summary_state::SetVerified<St>, S> {
        self._fields.5 = Option::Some(value.into());
        DomainSummaryBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainSummaryBuilder<St, S>
where
    St: domain_summary_state::State,
    St::Domain: domain_summary_state::IsSet,
    St::Kind: domain_summary_state::IsSet,
    St::Status: domain_summary_state::IsSet,
    St::Verified: domain_summary_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> DomainSummary<S> {
        DomainSummary {
            domain: self._fields.0.unwrap(),
            kind: self._fields.1.unwrap(),
            last_checked_at: self._fields.2,
            site_rkey: self._fields.3,
            status: self._fields.4.unwrap(),
            verified: self._fields.5.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> DomainSummary<S> {
        DomainSummary {
            domain: self._fields.0.unwrap(),
            kind: self._fields.1.unwrap(),
            last_checked_at: self._fields.2,
            site_rkey: self._fields.3,
            status: self._fields.4.unwrap(),
            verified: self._fields.5.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_place_wisp_v2_domain_getList() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("place.wisp.v2.domain.getList"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("domainSummary"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static("Summary of a claimed domain for list views."),
                    ),
                    required: Some(
                        vec![
                            SmolStr::new_static("domain"), SmolStr::new_static("kind"),
                            SmolStr::new_static("status"),
                            SmolStr::new_static("verified")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("domain"),
                            LexObjectProperty::String(LexString {
                                min_length: Some(3usize),
                                max_length: Some(253usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("kind"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("lastCheckedAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("siteRkey"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::RecordKey),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("status"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("verified"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: None,
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}