// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.privateSite.createShare
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, Datetime, RecordKey, Rkey, UriValue};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct CreateShare<S: BosStr = DefaultStr> {
    /// Restrict this link to a single account. The recipient must be signed in as this DID; the link alone grants nothing. Omit for a bearer link that anyone holding the URL can open, including people without an atproto account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audience_did: Option<Did<S>>,
    /// Minutes until this link expires. Omit for the configured default; 0 for no expiry of its own.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_minutes: Option<i64>,
    /// Optional human label for this link.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<S>,
    pub site_id: RecordKey<Rkey<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct CreateShareOutput<S: BosStr = DefaultStr> {
    /// Set when this link is restricted to a single account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audience_did: Option<Did<S>>,
    pub created_at: Datetime,
    /// The same credential on the site's own origin. Equivalent to `url`; useful when a link should not route through wisp.place.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direct_url: Option<UriValue<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Datetime>,
    pub share_id: S,
    pub site_id: RecordKey<Rkey<S>>,
    /// Short, human-friendly share link (wisp.place/p/<token>). Contains the credential and is returned exactly once.
    pub url: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum CreateShareError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "NotFound")]
    NotFound(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for CreateShareError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.privateSite.createShare` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `CreateShareOutput<S>` for this endpoint.*/
pub struct CreateShareResponse;
impl jacquard_common::xrpc::XrpcResp for CreateShareResponse {
    const NSID: &'static str = "place.wisp.v2.privateSite.createShare";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = CreateShareOutput<S>;
    type Err = CreateShareError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for CreateShare<S> {
    const NSID: &'static str = "place.wisp.v2.privateSite.createShare";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = CreateShareResponse;
}

/** Endpoint marker for the `place.wisp.v2.privateSite.createShare` procedure.

Path: `/xrpc/place.wisp.v2.privateSite.createShare`. The request payload type is `CreateShare<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct CreateShareRequest;
impl jacquard_common::xrpc::XrpcEndpoint for CreateShareRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.privateSite.createShare";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = CreateShare<S>;
    type Response = CreateShareResponse;
}

pub mod create_share_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type SiteId;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type SiteId = Unset;
    }
    ///State transition - sets the `site_id` field to Set
    pub struct SetSiteId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSiteId<St> {}
    impl<St: State> State for SetSiteId<St> {
        type SiteId = Set<members::site_id>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `site_id` field
        pub struct site_id(());
    }
}

/// Builder for constructing an instance of this type.
pub struct CreateShareBuilder<St: create_share_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Did<S>>, Option<i64>, Option<S>, Option<RecordKey<Rkey<S>>>),
    _type: PhantomData<fn() -> S>,
}

impl CreateShare<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> CreateShareBuilder<create_share_state::Empty, DefaultStr> {
        CreateShareBuilder::new()
    }
}

impl<S: BosStr> CreateShare<S> {
    /// Create a new builder for this type
    pub fn builder() -> CreateShareBuilder<create_share_state::Empty, S> {
        CreateShareBuilder::builder()
    }
}

impl CreateShareBuilder<create_share_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        CreateShareBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> CreateShareBuilder<create_share_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        CreateShareBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: create_share_state::State, S: BosStr> CreateShareBuilder<St, S> {
    /// Set the `audienceDid` field (optional)
    pub fn audience_did(mut self, value: impl Into<Option<Did<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `audienceDid` field to an Option value (optional)
    pub fn maybe_audience_did(mut self, value: Option<Did<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: create_share_state::State, S: BosStr> CreateShareBuilder<St, S> {
    /// Set the `expiryMinutes` field (optional)
    pub fn expiry_minutes(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `expiryMinutes` field to an Option value (optional)
    pub fn maybe_expiry_minutes(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: create_share_state::State, S: BosStr> CreateShareBuilder<St, S> {
    /// Set the `label` field (optional)
    pub fn label(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `label` field to an Option value (optional)
    pub fn maybe_label(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> CreateShareBuilder<St, S>
where
    St: create_share_state::State,
    St::SiteId: create_share_state::IsUnset,
{
    /// Set the `siteId` field (required)
    pub fn site_id(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> CreateShareBuilder<create_share_state::SetSiteId<St>, S> {
        self._fields.3 = Option::Some(value.into());
        CreateShareBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CreateShareBuilder<St, S>
where
    St: create_share_state::State,
    St::SiteId: create_share_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> CreateShare<S> {
        CreateShare {
            audience_did: self._fields.0,
            expiry_minutes: self._fields.1,
            label: self._fields.2,
            site_id: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> CreateShare<S> {
        CreateShare {
            audience_did: self._fields.0,
            expiry_minutes: self._fields.1,
            label: self._fields.2,
            site_id: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}