// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `place.wisp` Lexicon namespace/module.
pub mod auth_full_access;
pub mod auth_hosting;
pub mod auth_sites;
pub mod auth_webhooks;
pub mod fs;
pub mod settings;
pub mod subfs;
pub mod v2;