// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `place.wisp.v2.privateSite` Lexicon namespace/module.
pub mod create;
pub mod create_share;
pub mod delete;
pub mod list;
pub mod list_shares;
pub mod revoke_share;