// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.domain.addSite
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct AddSite<S: BosStr = DefaultStr> {
    /// Fully-qualified domain to map.
    pub domain: S,
    /// Owned place.wisp.fs record key to map this domain to.
    pub site_rkey: RecordKey<Rkey<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct AddSiteOutput<S: BosStr = DefaultStr> {
    pub domain: S,
    pub kind: AddSiteOutputKind<S>,
    pub mapped: bool,
    pub site_rkey: RecordKey<Rkey<S>>,
    pub status: AddSiteOutputStatus<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AddSiteOutputKind<S: BosStr = DefaultStr> {
    Wisp,
    Custom,
    Other(S),
}

impl<S: BosStr> AddSiteOutputKind<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Wisp => "wisp",
            Self::Custom => "custom",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "wisp" => Self::Wisp,
            "custom" => Self::Custom,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for AddSiteOutputKind<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for AddSiteOutputKind<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for AddSiteOutputKind<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for AddSiteOutputKind<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for AddSiteOutputKind<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for AddSiteOutputKind<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = AddSiteOutputKind<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            AddSiteOutputKind::Wisp => AddSiteOutputKind::Wisp,
            AddSiteOutputKind::Custom => AddSiteOutputKind::Custom,
            AddSiteOutputKind::Other(v) => AddSiteOutputKind::Other(v.into_static()),
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AddSiteOutputStatus<S: BosStr = DefaultStr> {
    PendingVerification,
    Verified,
    Other(S),
}

impl<S: BosStr> AddSiteOutputStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::PendingVerification => "pendingVerification",
            Self::Verified => "verified",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "pendingVerification" => Self::PendingVerification,
            "verified" => Self::Verified,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for AddSiteOutputStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for AddSiteOutputStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for AddSiteOutputStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for AddSiteOutputStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for AddSiteOutputStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for AddSiteOutputStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = AddSiteOutputStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            AddSiteOutputStatus::PendingVerification => {
                AddSiteOutputStatus::PendingVerification
            }
            AddSiteOutputStatus::Verified => AddSiteOutputStatus::Verified,
            AddSiteOutputStatus::Other(v) => AddSiteOutputStatus::Other(v.into_static()),
        }
    }
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum AddSiteError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidDomain")]
    InvalidDomain(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "NotFound")]
    NotFound(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for AddSiteError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidDomain(msg) => {
                write!(f, "InvalidDomain")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.domain.addSite` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `AddSiteOutput<S>` for this endpoint.*/
pub struct AddSiteResponse;
impl jacquard_common::xrpc::XrpcResp for AddSiteResponse {
    const NSID: &'static str = "place.wisp.v2.domain.addSite";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = AddSiteOutput<S>;
    type Err = AddSiteError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for AddSite<S> {
    const NSID: &'static str = "place.wisp.v2.domain.addSite";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = AddSiteResponse;
}

/** Endpoint marker for the `place.wisp.v2.domain.addSite` procedure.

Path: `/xrpc/place.wisp.v2.domain.addSite`. The request payload type is `AddSite<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct AddSiteRequest;
impl jacquard_common::xrpc::XrpcEndpoint for AddSiteRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.domain.addSite";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = AddSite<S>;
    type Response = AddSiteResponse;
}

pub mod add_site_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Domain;
        type SiteRkey;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Domain = Unset;
        type SiteRkey = Unset;
    }
    ///State transition - sets the `domain` field to Set
    pub struct SetDomain<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDomain<St> {}
    impl<St: State> State for SetDomain<St> {
        type Domain = Set<members::domain>;
        type SiteRkey = St::SiteRkey;
    }
    ///State transition - sets the `site_rkey` field to Set
    pub struct SetSiteRkey<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSiteRkey<St> {}
    impl<St: State> State for SetSiteRkey<St> {
        type Domain = St::Domain;
        type SiteRkey = Set<members::site_rkey>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `domain` field
        pub struct domain(());
        ///Marker type for the `site_rkey` field
        pub struct site_rkey(());
    }
}

/// Builder for constructing an instance of this type.
pub struct AddSiteBuilder<St: add_site_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<RecordKey<Rkey<S>>>),
    _type: PhantomData<fn() -> S>,
}

impl AddSite<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> AddSiteBuilder<add_site_state::Empty, DefaultStr> {
        AddSiteBuilder::new()
    }
}

impl<S: BosStr> AddSite<S> {
    /// Create a new builder for this type
    pub fn builder() -> AddSiteBuilder<add_site_state::Empty, S> {
        AddSiteBuilder::builder()
    }
}

impl AddSiteBuilder<add_site_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        AddSiteBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> AddSiteBuilder<add_site_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        AddSiteBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AddSiteBuilder<St, S>
where
    St: add_site_state::State,
    St::Domain: add_site_state::IsUnset,
{
    /// Set the `domain` field (required)
    pub fn domain(
        mut self,
        value: impl Into<S>,
    ) -> AddSiteBuilder<add_site_state::SetDomain<St>, S> {
        self._fields.0 = Option::Some(value.into());
        AddSiteBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AddSiteBuilder<St, S>
where
    St: add_site_state::State,
    St::SiteRkey: add_site_state::IsUnset,
{
    /// Set the `siteRkey` field (required)
    pub fn site_rkey(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> AddSiteBuilder<add_site_state::SetSiteRkey<St>, S> {
        self._fields.1 = Option::Some(value.into());
        AddSiteBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AddSiteBuilder<St, S>
where
    St: add_site_state::State,
    St::Domain: add_site_state::IsSet,
    St::SiteRkey: add_site_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> AddSite<S> {
        AddSite {
            domain: self._fields.0.unwrap(),
            site_rkey: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> AddSite<S> {
        AddSite {
            domain: self._fields.0.unwrap(),
            site_rkey: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}