// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.domain.verify
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Verify<S: BosStr = DefaultStr> {
    /// Custom domain FQDN to verify (for example, example.com).
    pub domain: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct VerifyOutput<S: BosStr = DefaultStr> {
    /// The CNAME target observed during verification, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cname_found: Option<S>,
    pub domain: S,
    /// Human-readable reason verification did not pass (when not verified).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<S>,
    pub kind: VerifyOutputKind<S>,
    pub status: VerifyOutputStatus<S>,
    /// The TXT value observed during verification, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub txt_found: Option<S>,
    pub verified: bool,
    /// Non-fatal advisory (for example, CNAME could not be confirmed due to flattening).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warning: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum VerifyOutputKind<S: BosStr = DefaultStr> {
    Custom,
    Other(S),
}

impl<S: BosStr> VerifyOutputKind<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Custom => "custom",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "custom" => Self::Custom,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for VerifyOutputKind<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for VerifyOutputKind<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for VerifyOutputKind<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for VerifyOutputKind<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for VerifyOutputKind<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for VerifyOutputKind<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = VerifyOutputKind<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            VerifyOutputKind::Custom => VerifyOutputKind::Custom,
            VerifyOutputKind::Other(v) => VerifyOutputKind::Other(v.into_static()),
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum VerifyOutputStatus<S: BosStr = DefaultStr> {
    PendingVerification,
    Verified,
    Other(S),
}

impl<S: BosStr> VerifyOutputStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::PendingVerification => "pendingVerification",
            Self::Verified => "verified",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "pendingVerification" => Self::PendingVerification,
            "verified" => Self::Verified,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for VerifyOutputStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for VerifyOutputStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for VerifyOutputStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for VerifyOutputStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for VerifyOutputStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for VerifyOutputStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = VerifyOutputStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            VerifyOutputStatus::PendingVerification => {
                VerifyOutputStatus::PendingVerification
            }
            VerifyOutputStatus::Verified => VerifyOutputStatus::Verified,
            VerifyOutputStatus::Other(v) => VerifyOutputStatus::Other(v.into_static()),
        }
    }
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum VerifyError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidDomain")]
    InvalidDomain(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "NotFound")]
    NotFound(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for VerifyError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidDomain(msg) => {
                write!(f, "InvalidDomain")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.domain.verify` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `VerifyOutput<S>` for this endpoint.*/
pub struct VerifyResponse;
impl jacquard_common::xrpc::XrpcResp for VerifyResponse {
    const NSID: &'static str = "place.wisp.v2.domain.verify";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = VerifyOutput<S>;
    type Err = VerifyError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for Verify<S> {
    const NSID: &'static str = "place.wisp.v2.domain.verify";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = VerifyResponse;
}

/** Endpoint marker for the `place.wisp.v2.domain.verify` procedure.

Path: `/xrpc/place.wisp.v2.domain.verify`. The request payload type is `Verify<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct VerifyRequest;
impl jacquard_common::xrpc::XrpcEndpoint for VerifyRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.domain.verify";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = Verify<S>;
    type Response = VerifyResponse;
}