// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.secret.create
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Datetime, RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Create<S: BosStr = DefaultStr> {
    /// Unique 1–64 character secret ID scoped to the caller DID. Use ASCII letters, digits, dots, underscores, and hyphens only.
    pub name: RecordKey<Rkey<S>>,
    /// Optional caller-supplied signing token: 32–256 printable ASCII characters, no whitespace. Omit it to have the server generate one. Use this to register a secret the receiving system already generated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct CreateOutput<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    pub name: S,
    /// The signing token. Only returned at creation time — store it now.
    pub token: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum CreateError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "AlreadyExists")]
    AlreadyExists(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for CreateError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AlreadyExists(msg) => {
                write!(f, "AlreadyExists")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.secret.create` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `CreateOutput<S>` for this endpoint.*/
pub struct CreateResponse;
impl jacquard_common::xrpc::XrpcResp for CreateResponse {
    const NSID: &'static str = "place.wisp.v2.secret.create";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = CreateOutput<S>;
    type Err = CreateError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for Create<S> {
    const NSID: &'static str = "place.wisp.v2.secret.create";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = CreateResponse;
}

/** Endpoint marker for the `place.wisp.v2.secret.create` procedure.

Path: `/xrpc/place.wisp.v2.secret.create`. The request payload type is `Create<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct CreateRequest;
impl jacquard_common::xrpc::XrpcEndpoint for CreateRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.secret.create";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = Create<S>;
    type Response = CreateResponse;
}

pub mod create_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Name;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Name = Unset;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type Name = Set<members::name>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `name` field
        pub struct name(());
    }
}

/// Builder for constructing an instance of this type.
pub struct CreateBuilder<St: create_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<RecordKey<Rkey<S>>>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl Create<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> CreateBuilder<create_state::Empty, DefaultStr> {
        CreateBuilder::new()
    }
}

impl<S: BosStr> Create<S> {
    /// Create a new builder for this type
    pub fn builder() -> CreateBuilder<create_state::Empty, S> {
        CreateBuilder::builder()
    }
}

impl CreateBuilder<create_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        CreateBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> CreateBuilder<create_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        CreateBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CreateBuilder<St, S>
where
    St: create_state::State,
    St::Name: create_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> CreateBuilder<create_state::SetName<St>, S> {
        self._fields.0 = Option::Some(value.into());
        CreateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: create_state::State, S: BosStr> CreateBuilder<St, S> {
    /// Set the `token` field (optional)
    pub fn token(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `token` field to an Option value (optional)
    pub fn maybe_token(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> CreateBuilder<St, S>
where
    St: create_state::State,
    St::Name: create_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Create<S> {
        Create {
            name: self._fields.0.unwrap(),
            token: self._fields.1,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Create<S> {
        Create {
            name: self._fields.0.unwrap(),
            token: self._fields.1,
            extra_data: Some(extra_data),
        }
    }
}