// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.secret.delete
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{RecordKey, Rkey};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Delete<S: BosStr = DefaultStr> {
    /// 1–64 character server-managed secret ID. Use ASCII letters, digits, dots, underscores, and hyphens only.
    pub name: RecordKey<Rkey<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum DeleteError {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(
        #[serde(skip_serializing_if = "Option::is_none")]
        Option<SmolStr>,
    ),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    #[serde(rename = "NotFound")]
    NotFound(#[serde(skip_serializing_if = "Option::is_none")] Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        #[serde(skip_serializing_if = "Option::is_none")]
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for DeleteError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `place.wisp.v2.secret.delete` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct DeleteResponse;
impl jacquard_common::xrpc::XrpcResp for DeleteResponse {
    const NSID: &'static str = "place.wisp.v2.secret.delete";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = DeleteError;
    fn decode_output<'de, S>(
        body: &'de [u8],
    ) -> Result<Self::Output<S>, jacquard_common::error::DecodeError>
    where
        S: BosStr + Deserialize<'de>,
    {
        if body.is_empty() {
            Ok(())
        } else {
            Err(jacquard_common::error::DecodeError::UnexpectedBody)
        }
    }
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for Delete<S> {
    const NSID: &'static str = "place.wisp.v2.secret.delete";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = DeleteResponse;
}

/** Endpoint marker for the `place.wisp.v2.secret.delete` procedure.

Path: `/xrpc/place.wisp.v2.secret.delete`. The request payload type is `Delete<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct DeleteRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DeleteRequest {
    const PATH: &'static str = "/xrpc/place.wisp.v2.secret.delete";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = Delete<S>;
    type Response = DeleteResponse;
}

pub mod delete_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Name;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Name = Unset;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type Name = Set<members::name>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `name` field
        pub struct name(());
    }
}

/// Builder for constructing an instance of this type.
pub struct DeleteBuilder<St: delete_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<RecordKey<Rkey<S>>>,),
    _type: PhantomData<fn() -> S>,
}

impl Delete<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> DeleteBuilder<delete_state::Empty, DefaultStr> {
        DeleteBuilder::new()
    }
}

impl<S: BosStr> Delete<S> {
    /// Create a new builder for this type
    pub fn builder() -> DeleteBuilder<delete_state::Empty, S> {
        DeleteBuilder::builder()
    }
}

impl DeleteBuilder<delete_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        DeleteBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> DeleteBuilder<delete_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        DeleteBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DeleteBuilder<St, S>
where
    St: delete_state::State,
    St::Name: delete_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<RecordKey<Rkey<S>>>,
    ) -> DeleteBuilder<delete_state::SetName<St>, S> {
        self._fields.0 = Option::Some(value.into());
        DeleteBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DeleteBuilder<St, S>
where
    St: delete_state::State,
    St::Name: delete_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Delete<S> {
        Delete {
            name: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Delete<S> {
        Delete {
            name: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}