// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.domains
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime, RecordKey, Rkey};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::place_wisp::v2::domains;
/// Registration metadata for a custom domain.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct CustomRegistration<S: BosStr = DefaultStr> {
    /// Challenge identifier used to derive DNS setup instructions.
    pub challenge_id: S,
    pub kind: S,
    pub verification: domains::Verification<S>,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_custom_registration_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Domain registration metadata for wisp.place subdomains and custom domains.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "place.wisp.v2.domains",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Domains<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    /// Lowercase FQDN for this registration (for example, alice.wisp.place or example.com).
    pub domain: S,
    pub registration: DomainsRegistration<S>,
    /// Optional place.wisp.fs record key currently mapped to this domain.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site_rkey: Option<RecordKey<Rkey<S>>>,
    pub updated_at: Datetime,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_domains_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub enum DomainsRegistration<S: BosStr = DefaultStr> {
    #[serde(rename = "place.wisp.v2.domains#wispRegistration")]
    WispRegistration(Box<domains::WispRegistration<S>>),
    #[serde(rename = "place.wisp.v2.domains#customRegistration")]
    CustomRegistration(Box<domains::CustomRegistration<S>>),
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct DomainsGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Domains<S>,
}

/// Latest verification state for a custom domain.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Verification<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_checked_at: Option<Datetime>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_error: Option<S>,
    pub method: VerificationMethod<S>,
    pub status: VerificationStatus<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<Datetime>,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_verification_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum VerificationMethod<S: BosStr = DefaultStr> {
    TxtDidV1,
    Other(S),
}

impl<S: BosStr> VerificationMethod<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::TxtDidV1 => "txt-did-v1",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "txt-did-v1" => Self::TxtDidV1,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for VerificationMethod<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for VerificationMethod<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for VerificationMethod<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for VerificationMethod<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for VerificationMethod<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for VerificationMethod<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = VerificationMethod<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            VerificationMethod::TxtDidV1 => VerificationMethod::TxtDidV1,
            VerificationMethod::Other(v) => VerificationMethod::Other(v.into_static()),
        }
    }
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum VerificationStatus<S: BosStr = DefaultStr> {
    Pending,
    Verified,
    Failed,
    Other(S),
}

impl<S: BosStr> VerificationStatus<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Pending => "pending",
            Self::Verified => "verified",
            Self::Failed => "failed",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "pending" => Self::Pending,
            "verified" => Self::Verified,
            "failed" => Self::Failed,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for VerificationStatus<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for VerificationStatus<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for VerificationStatus<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for VerificationStatus<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for VerificationStatus<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for VerificationStatus<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = VerificationStatus<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            VerificationStatus::Pending => VerificationStatus::Pending,
            VerificationStatus::Verified => VerificationStatus::Verified,
            VerificationStatus::Failed => VerificationStatus::Failed,
            VerificationStatus::Other(v) => VerificationStatus::Other(v.into_static()),
        }
    }
}

/// Registration for a first-party subdomain under the wisp.place base host.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct WispRegistration<S: BosStr = DefaultStr> {
    /// Subdomain label only (for example, alice).
    pub handle: S,
    pub kind: S,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_wisp_registration_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

impl<S: BosStr> Domains<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, DomainsRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

impl<S: BosStr> LexiconSchema for CustomRegistration<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.domains"
    }
    fn def_name() -> &'static str {
        "customRegistration"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_domains()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.challenge_id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("challenge_id"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.challenge_id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 8usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("challenge_id"),
                    min: 8usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct DomainsRecord;
impl XrpcResp for DomainsRecord {
    const NSID: &'static str = "place.wisp.v2.domains";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = DomainsGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<DomainsGetRecordOutput<S>> for Domains<S> {
    fn from(output: DomainsGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Domains<S> {
    const NSID: &'static str = "place.wisp.v2.domains";
    type Record = DomainsRecord;
}

impl Collection for DomainsRecord {
    const NSID: &'static str = "place.wisp.v2.domains";
    type Record = DomainsRecord;
}

impl<S: BosStr> LexiconSchema for Domains<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.domains"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_domains()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.domain;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 253usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("domain"),
                    max: 253usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.domain;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 3usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("domain"),
                    min: 3usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for Verification<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.domains"
    }
    fn def_name() -> &'static str {
        "verification"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_domains()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.last_error {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 1000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("last_error"),
                    max: 1000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for WispRegistration<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.domains"
    }
    fn def_name() -> &'static str {
        "wispRegistration"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_domains()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.handle;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 63usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("handle"),
                    max: 63usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.handle;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 3usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("handle"),
                    min: 3usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

fn deserialize_custom_registration_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}

pub mod custom_registration_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type ChallengeId;
        type Kind;
        type Verification;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type ChallengeId = Unset;
        type Kind = Unset;
        type Verification = Unset;
    }
    ///State transition - sets the `challenge_id` field to Set
    pub struct SetChallengeId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetChallengeId<St> {}
    impl<St: State> State for SetChallengeId<St> {
        type ChallengeId = Set<members::challenge_id>;
        type Kind = St::Kind;
        type Verification = St::Verification;
    }
    ///State transition - sets the `kind` field to Set
    pub struct SetKind<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetKind<St> {}
    impl<St: State> State for SetKind<St> {
        type ChallengeId = St::ChallengeId;
        type Kind = Set<members::kind>;
        type Verification = St::Verification;
    }
    ///State transition - sets the `verification` field to Set
    pub struct SetVerification<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetVerification<St> {}
    impl<St: State> State for SetVerification<St> {
        type ChallengeId = St::ChallengeId;
        type Kind = St::Kind;
        type Verification = Set<members::verification>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `challenge_id` field
        pub struct challenge_id(());
        ///Marker type for the `kind` field
        pub struct kind(());
        ///Marker type for the `verification` field
        pub struct verification(());
    }
}

/// Builder for constructing an instance of this type.
pub struct CustomRegistrationBuilder<
    St: custom_registration_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<S>, Option<domains::Verification<S>>),
    _type: PhantomData<fn() -> S>,
}

impl CustomRegistration<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> CustomRegistrationBuilder<
        custom_registration_state::Empty,
        DefaultStr,
    > {
        CustomRegistrationBuilder::new()
    }
}

impl<S: BosStr> CustomRegistration<S> {
    /// Create a new builder for this type
    pub fn builder() -> CustomRegistrationBuilder<custom_registration_state::Empty, S> {
        CustomRegistrationBuilder::builder()
    }
}

impl CustomRegistrationBuilder<custom_registration_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        CustomRegistrationBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> CustomRegistrationBuilder<custom_registration_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        CustomRegistrationBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CustomRegistrationBuilder<St, S>
where
    St: custom_registration_state::State,
    St::ChallengeId: custom_registration_state::IsUnset,
{
    /// Set the `challengeId` field (required)
    pub fn challenge_id(
        mut self,
        value: impl Into<S>,
    ) -> CustomRegistrationBuilder<custom_registration_state::SetChallengeId<St>, S> {
        self._fields.0 = Option::Some(value.into());
        CustomRegistrationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CustomRegistrationBuilder<St, S>
where
    St: custom_registration_state::State,
    St::Kind: custom_registration_state::IsUnset,
{
    /// Set the `kind` field (required)
    pub fn kind(
        mut self,
        value: impl Into<S>,
    ) -> CustomRegistrationBuilder<custom_registration_state::SetKind<St>, S> {
        self._fields.1 = Option::Some(value.into());
        CustomRegistrationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CustomRegistrationBuilder<St, S>
where
    St: custom_registration_state::State,
    St::Verification: custom_registration_state::IsUnset,
{
    /// Set the `verification` field (required)
    pub fn verification(
        mut self,
        value: impl Into<domains::Verification<S>>,
    ) -> CustomRegistrationBuilder<custom_registration_state::SetVerification<St>, S> {
        self._fields.2 = Option::Some(value.into());
        CustomRegistrationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CustomRegistrationBuilder<St, S>
where
    St: custom_registration_state::State,
    St::ChallengeId: custom_registration_state::IsSet,
    St::Kind: custom_registration_state::IsSet,
    St::Verification: custom_registration_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> CustomRegistration<S> {
        CustomRegistration {
            challenge_id: self._fields.0.unwrap(),
            kind: self._fields.1.unwrap(),
            verification: self._fields.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> CustomRegistration<S> {
        CustomRegistration {
            challenge_id: self._fields.0.unwrap(),
            kind: self._fields.1.unwrap(),
            verification: self._fields.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_place_wisp_v2_domains() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("place.wisp.v2.domains"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("customRegistration"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static("Registration metadata for a custom domain."),
                    ),
                    required: Some(
                        vec![
                            SmolStr::new_static("kind"),
                            SmolStr::new_static("challengeId"),
                            SmolStr::new_static("verification")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("challengeId"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Challenge identifier used to derive DNS setup instructions.",
                                    ),
                                ),
                                min_length: Some(8usize),
                                max_length: Some(64usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("kind"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("verification"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("#verification"),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Domain registration metadata for wisp.place subdomains and custom domains.",
                        ),
                    ),
                    key: Some(CowStr::new_static("any")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("domain"),
                                SmolStr::new_static("registration"),
                                SmolStr::new_static("createdAt"),
                                SmolStr::new_static("updatedAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("domain"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Lowercase FQDN for this registration (for example, alice.wisp.place or example.com).",
                                        ),
                                    ),
                                    min_length: Some(3usize),
                                    max_length: Some(253usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("registration"),
                                LexObjectProperty::Union(LexRefUnion {
                                    refs: vec![
                                        CowStr::new_static("#wispRegistration"),
                                        CowStr::new_static("#customRegistration")
                                    ],
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("siteRkey"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Optional place.wisp.fs record key currently mapped to this domain.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::RecordKey),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("updatedAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("verification"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "Latest verification state for a custom domain.",
                        ),
                    ),
                    required: Some(
                        vec![
                            SmolStr::new_static("status"), SmolStr::new_static("method")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("lastCheckedAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("lastError"),
                            LexObjectProperty::String(LexString {
                                max_length: Some(1000usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("method"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("status"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("verifiedAt"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("wispRegistration"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "Registration for a first-party subdomain under the wisp.place base host.",
                        ),
                    ),
                    required: Some(
                        vec![SmolStr::new_static("kind"), SmolStr::new_static("handle")],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("handle"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Subdomain label only (for example, alice).",
                                    ),
                                ),
                                min_length: Some(3usize),
                                max_length: Some(63usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("kind"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

fn deserialize_domains_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let mut data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    if let Some(extra_data) = &mut data {
        extra_data.remove("$type");
        if extra_data.is_empty() {
            data = None;
        }
    }
    Ok(data)
}

pub mod domains_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Domain;
        type Registration;
        type UpdatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Domain = Unset;
        type Registration = Unset;
        type UpdatedAt = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Domain = St::Domain;
        type Registration = St::Registration;
        type UpdatedAt = St::UpdatedAt;
    }
    ///State transition - sets the `domain` field to Set
    pub struct SetDomain<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDomain<St> {}
    impl<St: State> State for SetDomain<St> {
        type CreatedAt = St::CreatedAt;
        type Domain = Set<members::domain>;
        type Registration = St::Registration;
        type UpdatedAt = St::UpdatedAt;
    }
    ///State transition - sets the `registration` field to Set
    pub struct SetRegistration<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRegistration<St> {}
    impl<St: State> State for SetRegistration<St> {
        type CreatedAt = St::CreatedAt;
        type Domain = St::Domain;
        type Registration = Set<members::registration>;
        type UpdatedAt = St::UpdatedAt;
    }
    ///State transition - sets the `updated_at` field to Set
    pub struct SetUpdatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUpdatedAt<St> {}
    impl<St: State> State for SetUpdatedAt<St> {
        type CreatedAt = St::CreatedAt;
        type Domain = St::Domain;
        type Registration = St::Registration;
        type UpdatedAt = Set<members::updated_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `domain` field
        pub struct domain(());
        ///Marker type for the `registration` field
        pub struct registration(());
        ///Marker type for the `updated_at` field
        pub struct updated_at(());
    }
}

/// Builder for constructing an instance of this type.
pub struct DomainsBuilder<St: domains_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<S>,
        Option<DomainsRegistration<S>>,
        Option<RecordKey<Rkey<S>>>,
        Option<Datetime>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Domains<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> DomainsBuilder<domains_state::Empty, DefaultStr> {
        DomainsBuilder::new()
    }
}

impl<S: BosStr> Domains<S> {
    /// Create a new builder for this type
    pub fn builder() -> DomainsBuilder<domains_state::Empty, S> {
        DomainsBuilder::builder()
    }
}

impl DomainsBuilder<domains_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        DomainsBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> DomainsBuilder<domains_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        DomainsBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainsBuilder<St, S>
where
    St: domains_state::State,
    St::CreatedAt: domains_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> DomainsBuilder<domains_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        DomainsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainsBuilder<St, S>
where
    St: domains_state::State,
    St::Domain: domains_state::IsUnset,
{
    /// Set the `domain` field (required)
    pub fn domain(
        mut self,
        value: impl Into<S>,
    ) -> DomainsBuilder<domains_state::SetDomain<St>, S> {
        self._fields.1 = Option::Some(value.into());
        DomainsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainsBuilder<St, S>
where
    St: domains_state::State,
    St::Registration: domains_state::IsUnset,
{
    /// Set the `registration` field (required)
    pub fn registration(
        mut self,
        value: impl Into<DomainsRegistration<S>>,
    ) -> DomainsBuilder<domains_state::SetRegistration<St>, S> {
        self._fields.2 = Option::Some(value.into());
        DomainsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: domains_state::State, S: BosStr> DomainsBuilder<St, S> {
    /// Set the `siteRkey` field (optional)
    pub fn site_rkey(mut self, value: impl Into<Option<RecordKey<Rkey<S>>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `siteRkey` field to an Option value (optional)
    pub fn maybe_site_rkey(mut self, value: Option<RecordKey<Rkey<S>>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St, S: BosStr> DomainsBuilder<St, S>
where
    St: domains_state::State,
    St::UpdatedAt: domains_state::IsUnset,
{
    /// Set the `updatedAt` field (required)
    pub fn updated_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> DomainsBuilder<domains_state::SetUpdatedAt<St>, S> {
        self._fields.4 = Option::Some(value.into());
        DomainsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DomainsBuilder<St, S>
where
    St: domains_state::State,
    St::CreatedAt: domains_state::IsSet,
    St::Domain: domains_state::IsSet,
    St::Registration: domains_state::IsSet,
    St::UpdatedAt: domains_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Domains<S> {
        Domains {
            created_at: self._fields.0.unwrap(),
            domain: self._fields.1.unwrap(),
            registration: self._fields.2.unwrap(),
            site_rkey: self._fields.3,
            updated_at: self._fields.4.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Domains<S> {
        Domains {
            created_at: self._fields.0.unwrap(),
            domain: self._fields.1.unwrap(),
            registration: self._fields.2.unwrap(),
            site_rkey: self._fields.3,
            updated_at: self._fields.4.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn deserialize_verification_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}

fn deserialize_wisp_registration_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}