// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `place.wisp.v2.domain` Lexicon namespace/module.
pub mod add_site;
pub mod claim;
pub mod claim_subdomain;
pub mod delete;
pub mod get_list;
pub mod get_status;
pub mod verify;