// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `place.wisp.v2.site` Lexicon namespace/module.
pub mod delete;
pub mod get_domains;
pub mod get_list;