// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.wisp.v2.wh
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{Cid, Datetime, RecordKey, Rkey, UriValue};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::place_wisp::v2::wh;
/// Watch by AT-URI. at://did watches all collections for a DID. at://did/collection watches all records of that collection for a DID. at://did/collection/record watches a specific record.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct AtUri<S: BosStr = DefaultStr> {
    pub aturi: S,
    /// If true, also watch for records in any repo that reference this DID and collection.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backlinks: Option<bool>,
    /// If true, fire only for records in other repos that reference this scope. Events from the scope DID's own repo never fire, including records that reference itself. Implies backlinks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backlinks_only: Option<bool>,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_at_uri_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Webhook configuration for AT Protocol record events. Fires an HTTP POST to a URL when a matching record event is observed on the firehose.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "place.wisp.v2.wh",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Wh<S: BosStr = DefaultStr> {
    /// Timestamp of when the webhook was created.
    pub created_at: Datetime,
    /// Whether the webhook is active. Defaults to true if omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Which record events to trigger on. Defaults to all events if omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<WhEvents<S>>>,
    /// What to watch. An AT-URI scopes to a specific DID, collection, or record.
    pub scope: wh::AtUri<S>,
    /// Optional raw secret used to sign the webhook payload with HMAC-SHA256. Prefer secretId to avoid embedding plaintext values in PDS records.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secret: Option<S>,
    /// 1–64 character server-managed signing secret ID. Use ASCII letters, digits, dots, underscores, and hyphens only.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<RecordKey<Rkey<S>>>,
    /// HTTPS endpoint to POST the webhook payload to.
    pub url: UriValue<S>,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_wh_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum WhEvents<S: BosStr = DefaultStr> {
    Create,
    Update,
    Delete,
    Other(S),
}

impl<S: BosStr> WhEvents<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Create => "create",
            Self::Update => "update",
            Self::Delete => "delete",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "create" => Self::Create,
            "update" => Self::Update,
            "delete" => Self::Delete,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for WhEvents<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for WhEvents<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for WhEvents<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for WhEvents<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for WhEvents<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for WhEvents<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = WhEvents<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            WhEvents::Create => WhEvents::Create,
            WhEvents::Update => WhEvents::Update,
            WhEvents::Delete => WhEvents::Delete,
            WhEvents::Other(v) => WhEvents::Other(v.into_static()),
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct WhGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: jacquard_common::types::string::AtUri<S>,
    pub value: Wh<S>,
}

impl<S: BosStr> Wh<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, WhRecord>, UriError> {
        RecordUri::try_from_uri(jacquard_common::types::string::AtUri::new(uri)?)
    }
}

impl<S: BosStr> LexiconSchema for AtUri<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.wh"
    }
    fn def_name() -> &'static str {
        "atUri"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_wh()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct WhRecord;
impl XrpcResp for WhRecord {
    const NSID: &'static str = "place.wisp.v2.wh";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = WhGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<WhGetRecordOutput<S>> for Wh<S> {
    fn from(output: WhGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Wh<S> {
    const NSID: &'static str = "place.wisp.v2.wh";
    type Record = WhRecord;
}

impl Collection for WhRecord {
    const NSID: &'static str = "place.wisp.v2.wh";
    type Record = WhRecord;
}

impl<S: BosStr> LexiconSchema for Wh<S> {
    fn nsid() -> &'static str {
        "place.wisp.v2.wh"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_place_wisp_v2_wh()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.events {
            #[allow(unused_comparisons)]
            if value.len() > 3usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("events"),
                    max: 3usize,
                    actual: value.len(),
                });
            }
        }
        if let Some(ref value) = self.secret {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("secret"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.secret {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("secret"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.secret_id {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("secret_id"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.url;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 2048usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("url"),
                    max: 2048usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

fn deserialize_at_uri_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    Ok(data.filter(|extra_data| !extra_data.is_empty()))
}

fn lexicon_doc_place_wisp_v2_wh() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("place.wisp.v2.wh"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("atUri"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "Watch by AT-URI. at://did watches all collections for a DID. at://did/collection watches all records of that collection for a DID. at://did/collection/record watches a specific record.",
                        ),
                    ),
                    required: Some(vec![SmolStr::new_static("aturi")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("aturi"),
                            LexObjectProperty::String(LexString { ..Default::default() }),
                        );
                        map.insert(
                            SmolStr::new_static("backlinks"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("backlinksOnly"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Webhook configuration for AT Protocol record events. Fires an HTTP POST to a URL when a matching record event is observed on the firehose.",
                        ),
                    ),
                    key: Some(CowStr::new_static("any")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("scope"), SmolStr::new_static("url"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Timestamp of when the webhook was created.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("enabled"),
                                LexObjectProperty::Boolean(LexBoolean {
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("events"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Which record events to trigger on. Defaults to all events if omitted.",
                                        ),
                                    ),
                                    items: LexArrayItem::String(LexString {
                                        ..Default::default()
                                    }),
                                    max_length: Some(3usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("scope"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("#atUri"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("secret"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Optional raw secret used to sign the webhook payload with HMAC-SHA256. Prefer secretId to avoid embedding plaintext values in PDS records.",
                                        ),
                                    ),
                                    min_length: Some(1usize),
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("secretId"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "1–64 character server-managed signing secret ID. Use ASCII letters, digits, dots, underscores, and hyphens only.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::RecordKey),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("url"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "HTTPS endpoint to POST the webhook payload to.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Uri),
                                    max_length: Some(2048usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

fn deserialize_wh_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let mut data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    if let Some(extra_data) = &mut data {
        extra_data.remove("$type");
        if extra_data.is_empty() {
            data = None;
        }
    }
    Ok(data)
}

pub mod wh_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Scope;
        type Url;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Scope = Unset;
        type Url = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Scope = St::Scope;
        type Url = St::Url;
    }
    ///State transition - sets the `scope` field to Set
    pub struct SetScope<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetScope<St> {}
    impl<St: State> State for SetScope<St> {
        type CreatedAt = St::CreatedAt;
        type Scope = Set<members::scope>;
        type Url = St::Url;
    }
    ///State transition - sets the `url` field to Set
    pub struct SetUrl<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUrl<St> {}
    impl<St: State> State for SetUrl<St> {
        type CreatedAt = St::CreatedAt;
        type Scope = St::Scope;
        type Url = Set<members::url>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `scope` field
        pub struct scope(());
        ///Marker type for the `url` field
        pub struct url(());
    }
}

/// Builder for constructing an instance of this type.
pub struct WhBuilder<St: wh_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<bool>,
        Option<Vec<WhEvents<S>>>,
        Option<wh::AtUri<S>>,
        Option<S>,
        Option<RecordKey<Rkey<S>>>,
        Option<UriValue<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Wh<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> WhBuilder<wh_state::Empty, DefaultStr> {
        WhBuilder::new()
    }
}

impl<S: BosStr> Wh<S> {
    /// Create a new builder for this type
    pub fn builder() -> WhBuilder<wh_state::Empty, S> {
        WhBuilder::builder()
    }
}

impl WhBuilder<wh_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        WhBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> WhBuilder<wh_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        WhBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> WhBuilder<St, S>
where
    St: wh_state::State,
    St::CreatedAt: wh_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> WhBuilder<wh_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        WhBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: wh_state::State, S: BosStr> WhBuilder<St, S> {
    /// Set the `enabled` field (optional)
    pub fn enabled(mut self, value: impl Into<Option<bool>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `enabled` field to an Option value (optional)
    pub fn maybe_enabled(mut self, value: Option<bool>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: wh_state::State, S: BosStr> WhBuilder<St, S> {
    /// Set the `events` field (optional)
    pub fn events(mut self, value: impl Into<Option<Vec<WhEvents<S>>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `events` field to an Option value (optional)
    pub fn maybe_events(mut self, value: Option<Vec<WhEvents<S>>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> WhBuilder<St, S>
where
    St: wh_state::State,
    St::Scope: wh_state::IsUnset,
{
    /// Set the `scope` field (required)
    pub fn scope(
        mut self,
        value: impl Into<wh::AtUri<S>>,
    ) -> WhBuilder<wh_state::SetScope<St>, S> {
        self._fields.3 = Option::Some(value.into());
        WhBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: wh_state::State, S: BosStr> WhBuilder<St, S> {
    /// Set the `secret` field (optional)
    pub fn secret(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `secret` field to an Option value (optional)
    pub fn maybe_secret(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: wh_state::State, S: BosStr> WhBuilder<St, S> {
    /// Set the `secretId` field (optional)
    pub fn secret_id(mut self, value: impl Into<Option<RecordKey<Rkey<S>>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `secretId` field to an Option value (optional)
    pub fn maybe_secret_id(mut self, value: Option<RecordKey<Rkey<S>>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St, S: BosStr> WhBuilder<St, S>
where
    St: wh_state::State,
    St::Url: wh_state::IsUnset,
{
    /// Set the `url` field (required)
    pub fn url(
        mut self,
        value: impl Into<UriValue<S>>,
    ) -> WhBuilder<wh_state::SetUrl<St>, S> {
        self._fields.6 = Option::Some(value.into());
        WhBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> WhBuilder<St, S>
where
    St: wh_state::State,
    St::CreatedAt: wh_state::IsSet,
    St::Scope: wh_state::IsSet,
    St::Url: wh_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Wh<S> {
        Wh {
            created_at: self._fields.0.unwrap(),
            enabled: self._fields.1,
            events: self._fields.2,
            scope: self._fields.3.unwrap(),
            secret: self._fields.4,
            secret_id: self._fields.5,
            url: self._fields.6.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Wh<S> {
        Wh {
            created_at: self._fields.0.unwrap(),
            enabled: self._fields.1,
            events: self._fields.2,
            scope: self._fields.3.unwrap(),
            secret: self._fields.4,
            secret_id: self._fields.5,
            url: self._fields.6.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}